#ifndef __VERSION_H
#define __VERSION_H

#define SEGGER_DBUG

#define THIS_VERSION TYT_VERSION

#define TYT_VERSION 1
#define LENOVO_VERSION 2
#define LENOVO_ZZD_VERSION 3
#define ENG_VERSION 4 //英文EC20版本
#define EUX_VERSION 5
#define USA_VERSION 6
#define ZZD_VERSION 7
#define ZZD_ENG_VERSION 8
#define HWL_VERSION 9
#define KER_VERSION 10 //科瑞尔客户定制版

/*出厂默认版本号*/
#if THIS_VERSION == TYT_VERSION
#define CUSTOM_TIME
#define VER_SOFT "TYT_TP39PV2_V117"
#elif (THIS_VERSION == LENOVO_VERSION)
#define CUSTOM_TIME
#define LENOVO
#define VER_SOFT "LEN_CL860V2_V117"
#elif THIS_VERSION == LENOVO_ZZD_VERSION
#define CUSTOM_TIME
#define POC_ZZD
#define LENOVO
#define VER_SOFT "LEN_CL860V2_Z117"
#elif (THIS_VERSION == ENG_VERSION)
#define CUSTOM_TIME
#define LANGUAGE_ENGLISH
#define VER_SOFT "ENG_TP39PV2_V117"
#elif (THIS_VERSION == EUX_VERSION)
#define EC25_EUX //GSN
#define CUSTOM_TIME
#define LANGUAGE_ENGLISH
#define VER_SOFT "EUX_TP39PV2_V117"
#elif (THIS_VERSION == USA_VERSION)
#define EC25_USA //ip;180s;GSN
#define CUSTOM_TIME
#define LANGUAGE_ENGLISH
#define VER_SOFT "USA_TP39PV2_V117"
#elif THIS_VERSION == ZZD_VERSION
#define CUSTOM_TIME
#define POC_ZZD
#define VER_SOFT "ZZD_TP39PV2_V117"
#elif THIS_VERSION == ZZD_ENG_VERSION
#define LANGUAGE_ENGLISH
#define POC_ZZD
#define VER_SOFT "REA_TP39PV2_V001"

#elif THIS_VERSION == HWL_VERSION
#define CUSTOM_TIME
#define VER_SOFT "G20P_PLUS_+_V097"

#elif THIS_VERSION == KER_VERSION
#define CUSTOM_TIME
#define POC_ZZD
#define VER_SOFT "ZZD_GP59V02_V108"
#endif

//硬件版本
#define VER_HARDWARE "V1.0"

#endif
